### ISSUE TITLE
how to use @RequestMapping

### ISSUE THREAD

**Issue by ibmsoft** [9ci/grails-view-tools#24]
1、just a file in   src/main/java  HelloController
`
@Controller

public class HelloController {

    @RequestMapping("/hello")

    public String hello(Model model, @RequestParam(value="name", required=false, defaultValue="World") String name) {

        model.addAttribute("name", name);

        return "hello";

    }

}
`

2、views in src/main/webapp/hello.jsp
`
<html lang="en">

<head>

    <meta charset="UTF-8">

    <title>Hello</title>

</head>

<body>

Hello ${name}

</body>

</html>
`

3、use  http://localhost:8080/beans or mappings i can see the config
but when i access http://localhost:8080/hello
i get  following error
ax.servlet.ServletException: Could not resolve view with name 'hello' in servlet with name 'grailsDispatcherServlet'
	at org.springframework.web.servlet.DispatcherServlet.render(DispatcherServlet.java:1266)
	at org.springframework.web.servlet.DispatcherServlet.processDispatchResult(DispatcherServlet.java:1041)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:984)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:901)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:970)
	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:861)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:635)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:846)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:742)

**Comment by ibmsoft** [comment]
finally find the way ,custom view resolver order
